# Lab 1 - Pandas Intro

In [81]:
import pandas as pd

movies_df = pd.read_csv("movie.csv")
movies_df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

## Questions

**0.** What is the average IMDB Score of all the movies?

In [82]:
movies_df.imdb_score.mean()

6.4374288039056085

**1.** How many movies have "Star Wars" in the movie_title field?

In [83]:
from re import S

st_movies = movies_df[movies_df.movie_title.str.contains("Star Wars")]
len(st_movies)

8

**2.** Which movie has the highest IMDB Score? What is that score?

In [84]:
movies_df.groupby('movie_title')[['imdb_score']].max().sort_values(['imdb_score'], ascending=False)

                                imdb_score
movie_title
Towering Inferno                       9.5
The Shawshank Redemption               9.3
The Godfather                          9.2
Dekalog                                9.1
Kickboxer: Vengeance                   9.1
...                                    ...
The Helix... Loaded                    1.9
Disaster Movie                         1.9
Superbabies: Baby Geniuses 2           1.9
Foodfight!                             1.7
Justin Bieber: Never Say Never         1.6

[4916 rows x 1 columns]

**3**. Which movie has the lowest IMDB Score? What is that score?

In [85]:
#print(movies_df.imdb_score.min())
movies_df.groupby('movie_title')[['imdb_score']].min().sort_values(['imdb_score'], ascending=True)

                                imdb_score
movie_title
Justin Bieber: Never Say Never         1.6
Foodfight!                             1.7
Superbabies: Baby Geniuses 2           1.9
Disaster Movie                         1.9
The Helix... Loaded                    1.9
...                                    ...
Dekalog                                9.1
Kickboxer: Vengeance                   9.1
The Godfather                          9.2
The Shawshank Redemption               9.3
Towering Inferno                       9.5

[4916 rows x 1 columns]

**4.** For each director, how many movies have they directed (from this dataset)?

In [86]:
movies_df.director_name.value_counts()

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
John Putch           1
Luca Guadagnino      1
Sam Fell             1
Dan Fogelman         1
Daniel Hsia          1
Name: director_name, Length: 2397, dtype: int64

**5.** What's the average duration of Action movies?

In [87]:
action_movies = movies_df[movies_df.genres.str.contains("Action")]
action_movies.duration.mean()

110.67657657657658

**6.** Which PG-13 movie had the biggest budget?

In [117]:
# first sort movies based on rating
# then search that list for biggest budget
pg_movie = movies_df.dropNa(thresh=2)

pg_movies = movies_df[movies_df.content_rating.str.contains("PG-13")]

AttributeError: 'DataFrame' object has no attribute 'dropNa'

**7.** How many movies were made in each year (title_year)?

In [89]:
movies_df.title_year.value_counts()

2009.0    253
2014.0    243
2006.0    233
2013.0    231
2010.0    225
         ...
1932.0      1
1916.0      1
1934.0      1
1925.0      1
1920.0      1
Name: title_year, Length: 91, dtype: int64

**8.** How many movies had more than 10000 movie_facebook_likes?

In [90]:
mask = movies_df.movie_facebook_likes <= 10000
mask.sum

movies_df[mask]

movies_df[movies_df.movie_facebook_likes <= 10000].movie_facebook_likes.size

3894


**9.** How many movies have "Tom Hanks" (as actor1, actor2, or actor3)?

In [91]:
mask = (
    (movies_df.actor_1_name == "Tom Hanks") | 
    (movies_df.actor_2_name == "Tom Hanks") |
    (movies_df.actor_3_name == "Tom Hanks")
)

#mask = movies_df.actor_1_name.isin(["Kevin Hart", "Dwayne Johnson"])
mask

movies_df[mask]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
43,Color,Lee Unkrich,453.0,103.0,125.0,721.0,John Ratzenberger,15000.0,414984497.0,Adventure|Animation|Comedy|Family|Fantasy,...,733.0,English,USA,G,200000000.0,2010.0,1000.0,8.3,1.85,30000
91,Color,Robert Zemeckis,188.0,100.0,0.0,267.0,Eddie Deezen,15000.0,665426.0,Adventure|Animation|Family|Fantasy,...,444.0,English,USA,G,165000000.0,2004.0,726.0,6.6,2.35,10000
129,Color,Ron Howard,298.0,146.0,2000.0,294.0,Ayelet Zurer,15000.0,133375846.0,Mystery|Thriller,...,435.0,English,USA,PG-13,150000000.0,2009.0,745.0,6.7,2.35,0
205,Color,Ron Howard,294.0,174.0,2000.0,362.0,Seth Gabel,15000.0,217536138.0,Mystery|Thriller,...,1966.0,English,USA,PG-13,125000000.0,2006.0,574.0,6.6,2.35,0
307,Color,Tom Tykwer,511.0,172.0,670.0,1000.0,Jim Sturgess,15000.0,27098580.0,Drama|Sci-Fi,...,828.0,English,Germany,R,102000000.0,2012.0,5000.0,7.5,2.35,124000
349,Color,John Lasseter,191.0,82.0,487.0,967.0,John Ratzenberger,15000.0,245823397.0,Adventure|Animation|Comedy|Family|Fantasy,...,515.0,English,USA,G,90000000.0,1999.0,1000.0,7.9,1.85,0
390,Color,Robert Zemeckis,221.0,143.0,0.0,272.0,Paul Sanchez,15000.0,233630478.0,Adventure|Drama|Romance,...,1051.0,English,USA,PG-13,90000000.0,2000.0,410.0,7.7,1.85,23000
451,Color,Sam Mendes,226.0,117.0,0.0,818.0,Jennifer Jason Leigh,15000.0,104054514.0,Crime|Drama|Thriller,...,1009.0,English,USA,R,80000000.0,2002.0,1000.0,7.7,2.35,0
530,Color,Steven Spielberg,151.0,128.0,14000.0,232.0,Chi McBride,15000.0,77032279.0,Comedy|Drama,...,596.0,English,USA,PG-13,60000000.0,2004.0,466.0,7.3,1.85,16000
534,Color,Mike Nichols,269.0,102.0,0.0,15000.0,Tom Hanks,22000.0,66636385.0,Biography|Comedy|Drama|History,...,289.0,English,USA,R,75000000.0,2007.0,15000.0,7.1,1.85,0
641,Color,Steven Spielberg,219.0,169.0,14000.0,13000.0,Vin Diesel,15000.0,216119491.0,Action|Drama|War,...,2277.0,English,USA,R,70000000.0,1998.0,14000.0,8.6,1.85,22000
648,Color,Ron Howard,159.0,140.0,2000.0,552.0,Miko Hughes,15000.0,172071312.0,Adventure|Drama|History,...,296.0,English,USA,PG,62000000.0,1995.0,968.0,7.6,2.35,5000
651,Color,Nora Ephron,153.0,119.0,0.0,744.0,Jean Stapleton,15000.0,115731542.0,Comedy|Drama|Romance,...,556.0,English,USA,PG,65000000.0,1998.0,793.0,6.5,1.85,0
704,Color,Frank Darabont,186.0,189.0,0.0,693.0,Jeffrey DeMunn,15000.0,136801374.0,Crime|Drama|Fantasy|Mystery,...,1377.0,English,USA,R,60000000.0,1999.0,745.0,8.5,1.85,30000
827,Black and White,Robert Zemeckis,149.0,142.0,0.0,194.0,Siobhan Fallon Hogan,15000.0,329691196.0,Comedy|Drama,...,1398.0,English,USA,PG-13,55000000.0,1994.0,294.0,8.8,2.35,59000
836,Color,Paul Greengrass,491.0,134.0,521.0,186.0,Chris Mulkey,15000.0,107100855.0,Biography|Drama|Thriller,...,527.0,English,USA,PG-13,55000000.0,2013.0,535.0,7.9,2.35,65000
902,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,667.0,English,USA,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000
1185,Black and White,Penny Marshall,41.0,128.0,545.0,251.0,Lori Petty,15000.0,107458785.0,Comedy|Drama|Sport,...,166.0,English,USA,PG,40000000.0,1992.0,923.0,7.2,2.35,0
1213,Color,Steven Spielberg,459.0,142.0,14000.0,423.0,Mark Rylance,15000.0,72306065.0,Drama|History|Thriller,...,355.0,English,USA,PG-13,40000000.0,2015.0,535.0,7.6,2.35,55000
1258,Color,Stephen Daldry,283.0,129.0,335.0,64.0,Thomas Horn,15000.0,31836745.0,Adventure|Drama|Mystery,...,341.0,English,USA,PG-13,40000000.0,2011.0,467.0,6.9,2.35,39000
1415,Color,John Lee Hancock,405.0,125.0,102.0,825.0,Ruth Wilson,15000.0,83299761.0,Biography|Comedy|Drama|History|Music,...,306.0,English,USA,PG-13,35000000.0,2013.0,2000.0,7.5,2.35,39000
1426,Color,Ethan Coen,193.0,104.0,1000.0,939.0,Tom Hanks,24000.0,39692139.0,Comedy|Crime|Thriller,...,400.0,English,USA,R,35000000.0,2004.0,15000.0,6.2,1.85,0
1572,Color,John Lasseter,166.0,74.0,487.0,802.0,John Ratzenberger,15000.0,191796233.0,Adventure|Animation|Comedy|Family|Fantasy,...,391.0,English,USA,G,30000000.0,1995.0,1000.0,8.3,1.85,0
1645,Color,Tom Hanks,218.0,98.0,15000.0,392.0,Rob Riggle,15000.0,35565975.0,Comedy|Drama|Romance,...,184.0,English,USA,PG-13,30000000.0,2011.0,839.0,6.1,2.35,0
2364,Color,Penny Marshall,99.0,130.0,545.0,697.0,Jon Lovitz,15000.0,114968774.0,Comedy|Drama|Family|Fantasy|Romance,...,204.0,English,USA,PG,18000000.0,1988.0,11000.0,7.3,1.85,0
2536,Color,Jonathan Demme,68.0,125.0,438.0,372.0,Tom Hanks,18000.0,77324422.0,Drama,...,261.0,English,USA,PG-13,26000000.0,1993.0,15000.0,7.7,1.85,0
3300,Color,Ron Howard,43.0,111.0,2000.0,51.0,Howard Morris,15000.0,69800000.0,Comedy|Fantasy|Romance,...,99.0,English,USA,PG,8000000.0,1984.0,161.0,6.2,1.85,0
4095,Color,Tom Hanks,75.0,149.0,15000.0,982.0,Charlize Theron,15000.0,25809813.0,Comedy|Drama|Music,...,212.0,English,USA,PG,26000000.0,1996.0,9000.0,6.9,1.37,0

**10.**  What are the movies and number of voted users (num_voted_users) for movies that have less than 2 faces in the poster (facenumber_in_poster)?

In [99]:
# first narrow down to movies that have less than 2 faces in the poster
# then figure out the movies and number of voted users for those movies

pf_movies = movies_df[(movies_df.facenumber_in_poster < 2)]
pf_movies[ [ "movie_title", "num_voted_users", "facenumber_in_poster" ] ]

,movie_title,num_voted_users,facenumber_in_poster
0,Avatar,886204,0.0
1,Pirates of the Caribbean: At World's End,471220,0.0
2,Spectre,275868,1.0
3,The Dark Knight Rises,1144337,0.0
4,Star Wars: Episode VII - The Force Awakens,8,0.0
...,...,...,...
4909,The Mongol King,36,0.0
4910,Newlyweds,1338,1.0
4912,The Following,73839,1.0
4913,A Plague So Pleasant,38,0.0
4915,My Date with Drew,4285,0.0

**11.** What are the directors and number of director facebook likes for movies made beteween 2000 and 2004 (inclusive) sorted in descending order of director facebook likes?

In [102]:
movie_year = movies_df[ (movies_df.title_year >= 2000) & (movies_df.title_year <= 2004) ]
movie_year[ ["director_name", "director_facebook_likes","title_year"]].sort_values("director_facebook_likes", ascending=False)

#movies_df[["director_name", "director_facebook_likes","title_year"]].sort_values("director_facebook_likes", ascending=False)

             director_name  director_facebook_likes  title_year
1057     Christopher Nolan                  22000.0      2002.0
3646     Christopher Nolan                  22000.0      2000.0
1034         David Fincher                  21000.0      2002.0
2849     Denzel Washington                  18000.0      2002.0
2023          Kevin Spacey                  18000.0      2004.0
...                    ...                      ...         ...
2081           Kevin Smith                      0.0      2001.0
1935  Paul Thomas Anderson                      0.0      2002.0
1896              John Eng                      0.0      2003.0
1895       Cathy Malkasian                      0.0      2002.0
31               Sam Raimi                      0.0      2004.0

[932 rows x 3 columns]

**12.** What are the missing values (NaN)? (in class practice)

In [94]:
#movies_df.duration.isna().sum()

In [95]:
#movies_df.duration.isna().sum() / len(movies_df)
#movies_df.duration.fillna( movies_df.duration.median(), inplace=True)
#movies_df.loc[4].duration